# Generated by Django 5.1.4 on 2024-12-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="description",
            field=models.TextField(default="Default description", verbose_name="Описание"),
        ),
    ]
